### PR TITLE
WIP: Feature/realtime react chat

### PR DESCRIPTION
**Pull request by 8byr0**

### CODE REVIEW

**Comment by akshayjj1997** [comment]
Is Search Contact implemented?

**Comment by 8byr0** [comment]
@akshayjj1997 Not yet, it will be my next topic before implementing redux !

**Comment by YourTechBud** [comment]
Do we really need so many fonts? Can't we just use a Google font and keep things lean?

**Comment by 8byr0** [comment]
You're right @YourTechBud. I included all the fonts variants to allow text customization in the future but I agree it's overkill. I'll remove the ones I don't use and reimport then if needed!

**Comment by YourTechBud** [comment]
Great! By when do you think we can get this done @8byr0?

**Comment by 8byr0** [comment]
@YourTechBud I think that it should be fully ready in about a week, depending on my free time to work on this !

**Comment by 8byr0** [comment]
Hello guys, 
I need to agree on the data structure with you. Here's what I suggest :
 
# Collections
## Messages
A set of documents, each one matching the following pattern:
```js
{
     "_id" : "aLongGeneratedMongoID",
     "from": "idOfTheUserWhoSentTheMessage",
     "to": "idOfTheUserWhoReceivedTheMessage",
     "text" : "My message text, hello world !",
     "sendDate": "timestamp",
     "read" : "true | false"
}
```

## Users
Using auth email module.

# Client side
## Store
The redux store will be composed of 2 reducers, `chat` and `user`

### Chat
```js
{
    "isLoadingFromServer": "true | false",
    "isLoadingDiscussion": "true | false",
    "list": [
        {
            "user": {}, // user document queried from database
            "messages": [] // list of messages queried from database
        }
    ]
```

## Loading data
To load data in the client:
1. fetch users
2. fetch messages 
3. create a conversation for each user
4. dispatch messages to belonging conversation
5. dispatch created list to redux (that will be binded to components)



@akshayjj1997 @YourTechBud What do you think ? Does it seems relevant to you ?

**Comment by YourTechBud** [comment]
Maybe @Jayesh333 should have a look at this!

**Comment by Jayesh333** [comment]
```
{
    "isLoadingFromServer": "true | false",
    "isLoadingDiscussion": "true | false",
    "list": [
        {
            "user": {}, // user document queried from database
            "messages": [] // list of messages queried from database
        }
    ]
}
```
- If I have guessed it right then  `user` in the `list` above is the list of `users`? So we can change its name to `users`. And we can move the `users` and `messages` out of the `list` field.
- Is `messages` list of all the messages or just with a particular person? 
 

For the `isActive` part I have this idea:
After a user logs in he can periodically (every 5-10 seconds) update the `lastSeen` field with the currentTimeStamp for his document in `users` collection.

**Comment by 8byr0** [comment]
> ```
> {
>     "isLoadingFromServer": "true | false",
>     "isLoadingDiscussion": "true | false",
>     "list": [
>         {
>             "user": {}, // user document queried from database
>             "messages": [] // list of messages queried from database
>         }
>     ]
> }
> ```
> * If I have guessed it right then  `user` in the `list` above is the list of `users`? So we can change its name to `users`. And we can move the `users` and `messages` out of the `list` field.
> * Is `messages` list of all the messages or just with a particular person?
> 
> For the `isActive` part I have this idea:
> After a user logs in he can periodically (every 5-10 seconds) update the `lastSeen` field with the currentTimeStamp for his document in `users` collection.

Not exactly ! 

Here is our store
```javascript
{
    user: {
        // this reducer contains local user data
    },
    chat: {
        // this one handles all datas related to chat
    }
}
```

Let's take an example (this is our redux store):
```javascript
{
    user: {
        // I am John DOE and this is the place where my data is stored
        _id: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f",
        name: "John DOE",
        lastSeen: "timestamp",
    },
    chat: {
        isLoadingFromServer: false, // will be true when querying data at init (used to display progress bars)
        isLoadingDiscussion: false, // Will be true between a click on an item in chats list and discussion fully shown on the right part of the screen
        list: [ // A list of all my discussions 
            {
                user: { // Pal data
                    _id: "dfgh963556jklm-2e33-4cf3-9a75-f6fg5r5e4",
                    name: "Bill GATES",
                    lastSeen: "timestamp",
                },
                messages: [
                    {
                        from: "dfgh963556jklm-2e33-4cf3-9a75-f6fg5r5e4", // This is Bill Gates' _id
                        to: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
                        sendDate: "timestamp",
                        text: "Hello John, I'm Bill Gates",
                        read: true // I've read Bill's message
                    },
                    {
                        from: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
                        to: "dfgh963556jklm-2e33-4cf3-9a75-f6fg5r5e4", // This is Bill Gates' _id
                        sendDate: "timestamp",
                        text: "Hello Bill, nice to meet you !",
                        read: false // Bill has not read my message
                    }
                ]
            },
            {
                user: { // Pal data
                    _id: "e63e5f2g5g-6z8e-4cf3-9a75-f6fg5r5e4",
                    name: "Steve JOBS",
                    lastSeen: "timestamp",
                },
                messages: [
                    {
                        from: "e63e5f2g5g-6z8e-4cf3-9a75-f6fg5r5e4", // This is Steve JOBS' _id
                        to: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
                        sendDate: "timestamp",
                        text: "Hello John, I'm Steve",
                        read: true // I've read Steve's message
                    },
                    {
                        from: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
                        to: "e63e5f2g5g-6z8e-4cf3-9a75-f6fg5r5e4", // This is Steve JOBS' _id
                        sendDate: "timestamp",
                        text: "Hello Steve, nice to meet you !",
                        read: false // Steve has not read my message
                    }
                ]
            }
        ] 
    }
}
```


So to get to this store we've had to:
1. fetch users
```javascript
[
    {
        _id: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f",
        name: "John DOE",
        lastSeen: "timestamp",
    },
    { 
        _id: "e63e5f2g5g-6z8e-4cf3-9a75-f6fg5r5e4",
        name: "Steve JOBS",
        lastSeen: "timestamp",
    },
    {
        _id: "dfgh963556jklm-2e33-4cf3-9a75-f6fg5r5e4",
        name: "Bill GATES",
        lastSeen: "timestamp",
    }
]
```
2. fetch messages
```javascript
[
    {
        from: "dfgh963556jklm-2e33-4cf3-9a75-f6fg5r5e4", // This is Bill Gates' _id
        to: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
        sendDate: "timestamp",
        text: "Hello John, I'm Bill Gates",
        read: true // I've read Bill's message
    },
    {
        from: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
        to: "dfgh963556jklm-2e33-4cf3-9a75-f6fg5r5e4", // This is Bill Gates' _id
        sendDate: "timestamp",
        text: "Hello Bill, nice to meet you !",
        read: false // Bill has not read my message
    },
    {
        from: "e63e5f2g5g-6z8e-4cf3-9a75-f6fg5r5e4", // This is Steve JOBS' _id
        to: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
        sendDate: "timestamp",
        text: "Hello John, I'm Steve",
        read: true // I've read Steve's message
    },
    {
        from: "d7f5ba7f-2e33-4cf3-9a75-fc2f3f272b4f", // This is my _id
        to: "e63e5f2g5g-6z8e-4cf3-9a75-f6fg5r5e4", // This is Steve JOBS' _id
        sendDate: "timestamp",
        text: "Hello Steve, nice to meet you !",
        read: false // Steve has not read my message
    }
]
```
3. Combine these informations to discussions
```javascript
// See store.chat.list in reducer
```


Does it make more sense to you ?

**Comment by 8byr0** [comment]
Just merged a dev branch into this one (WIP still running). 
Tasks overview
- [x] Implement UI / behavior
- [x] Implement redux
- [x] Allow users to sign in
- [x] Allow users to sign up
- [x] Fetch chats, users and messages
- [x] Realtime refresh chats
- [x] Create a global chat
- [ ] handle error cases and add notify users when occurring
- [ ] comment the code that's not commented
- [ ] refactor the things that need to be 
- [ ] fix a bug in global chat
- [ ] Write README
- [ ] rewrite config.yaml to handle security 
- [ ] add user directory (list users and start chat)
- [ ] add remember me checkbox to sign in/up forms

**Comment by YourTechBud** [comment]
@8byr0 any eta on this? By when do you expect to finish it?

**Comment by 8byr0** [comment]
@YourTechBud Yes, most of the features are now done so the major part is doc/refactoring but as my laptop does not like Singapore's thunderstorms, I need to wait for it to be fixed (should be good in a few days according to the repair company). 
If I get my laptop back soon it should be ok by friday!

**Comment by YourTechBud** [comment]
Haha! Let me know when you are done @8byr0. Will merge it right in.

**Comment by 8byr0** [comment]
@YourTechBud You can follow my progress on the ticket above https://github.com/spaceuptech/sample-apps/pull/2#issuecomment-488228354 !

**Comment by YourTechBud** [comment]
@8byr0 does it still require to add a document in the database in order for the "All" chat to work?

**Comment by 8byr0** [comment]
@YourTechBud no, it is no longer required !

**Comment by YourTechBud** [comment]
@8byr0 great. It seems like its done now. Just the security rules are pending. I can probably add that later. I really appreciate your contribution and specially the time you have put in. Haven't got a change to go through the entire code yet. Will do that tomorrow. Thanks a ton buddy.

One last request though. Can we get rid of the fonts? Lets keep the project as light as possible?

**Comment by 8byr0** [comment]
Actually my free time is quite difficult to find so if you can write security rules it would help ! Btw I will write them in English for each collection so you'll only have to translate in space cloud way ! 
I will remove unnecessary fonts this evening !

**Comment by YourTechBud** [comment]
Sounds like a plan

**Comment by 8byr0** [comment]
@YourTechBud here are the rules for each collection :
## Messages
- create
Allow if message.chat_id is a chat with chat.from==user._id or chat.to==user._id

- read
Allow if message.chat_id is a chat with chat from==user._id or chat.to==user._id

- update 
Allow if message.chat_id is a chat with from==user._id or to==user._id
And if message.to ==user._id
Only allow update of message.read (boolean, only from false to true)

- delete
Deny

## Users
- create
Allow

- read 
Authenticated (do not return pass)

- update
Allow if user._id is request's user id

- delete
Deny

## chats
- create 
Allow if chat.from==user._id

- read
Allow if chat.from==user._id or chat to==user._id

- update 
Deny

- delete
Deny

**Comment by YourTechBud** [comment]
@8byr0 You are not calling get users anywhere. The app doesn't seem to be loading the users currently logged into the app

**Comment by 8byr0** [comment]
I'm calling users real-time,  which will update users list. You can see connected users in users list ! The left panel is only intended to show started chats.

**Comment by YourTechBud** [comment]
Got it. Your timeout to show whether a member is active or not is pretty tight. While i have both the users live the last active feature keeps bouncing

**Comment by 8byr0** [comment]
Got it, I will have a look this evening.

**Pull request merged**
